### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jaanos** [sabrinacalcina/Nepremicnine#1]
Na repozitoriju nimate datoteke `.gitignore`, a se vam je nanj že izmuznilo nekaj datotek, ki nanj ne sodijo. Svetujem, da začnete z datoteko z [vzorca](https://github.com/jaanos/OPB-bottle/blob/master/.gitignore) - ta že poskrbi za mapo `__pycache__` in datoteko `auth.py`, kjer boste imeli (vsak svoje) podatke za priklop na bazo, poleg tega pa dodajte še vrstici `.ipynb_checkpoints` in `.vscode`, da vam ne bo nalagalo datotek iz teh map.

Sama prisotnost vnosov v `.gitignore` sicer ne bo pobrisala teh map, tako da jih bo potrebno ročno pobrisati - eden od vas naj to torej naredi in commita, ostala pa naredita pull, da pridobita spremembe k sebi. V lokalni kopiji se bodo mape seveda ponovno pojavile, le na repozitoriju jih več ne bo, in git vam jih več ne bo ponujal za vključitev v commit.

**Comment by sabrinacalcina** [comment]
Predlagano sem popravila. Ali je sedaj vredu?

**Comment by jaanos** [comment]
Glede `.gitignore` je sedaj urejeno, opažam pa, da si @DomenFlakusBosilj v `auth_public.py` dal svoje geslo za bazo - to je sedaj za vekomaj objavljeno na internetu, tako da svetujem, da ga zamenjaš.

Datoteka `auth_public.py` je namenjena prijavi z uporabnikom, ki ima ravno tolikšne pravice, kot jih potrebuje aplikacija - v ta namen je na bazi pripravljen uporabnik `javnost`. Kot rečeno, boste svoja gesla imeli v datoteki `auth.py` (glejte tudi melamalej/Knjiznica#1), kar boste potrebovali za uvoz podatkov (in ne za glavno aplikacijo).

**Comment by DomenFlakusBosilj** [comment]
Geslo imam spremenjeno in datoteka auth_public.py je popravljena

**Comment by jaanos** [comment]
V redu, potem bom kar zaprl issue. Seveda ga lahko tudi sami zaprete, ko uredite, kar je treba.
